### ISSUE TITLE
Readme xcodebuild syntax issue

### ISSUE THREAD

**Issue by Baschdi** [bielikb/xcframeworks#11]
The following content in the readme isn't valid syntax and won't succeed:
```
-destination destination="generic/platform=iOS Simulator" \
...
-destination destination="generic/platform=iOS" \
```

It should be:
```
-destination "generic/platform=iOS Simulator" \
...
-destination "generic/platform=iOS" \
```

I think there's a total of 3 mentions of the incorrect syntax.

**Comment by bielikb** [comment]
@Baschdi thanks for spotting this! I just corrected it in the README ;)
