### ISSUE TITLE
`lipo` is not deprecated and the suggestion to not use it is misleading

### ISSUE THREAD

**Issue by dcow** [bielikb/xcframeworks#12]
View my explanation here: https://developer.apple.com/forums/thread/666335?answerId=685927022#685927022

I think the misunderstanding is that Xcode simply has a better UX now for creating frameworks so if you're using Xcode to build your code you no longer need to add manual build phases and manually invoke `lipo`. But the notion of fat binaries has not gone anywhere and, if you're doing this manually (anyone not using Xcode to build their libraries, and even some who are) then you still need to be putting fat binaries into the top level xcframework. It can't happen any other way (=

**Comment by bielikb** [comment]
Hi @dcow yeah good spot! Ill fix this :)
