### ISSUE TITLE
Pass SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO to xcodebuild

### ISSUE THREAD

**Issue by Cyberbeni** [bielikb/xcframeworks#18]
Otherwise the xcframework breaks lldb on machines other than the one that built it: https://developer.apple.com/videos/play/wwdc2022/110370/?time=1096

**Comment by OdNairy** [comment]
@Cyberbeni you've closed the ticket. Does it mean that we don't need a `SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO` in xcodebuild?

**Comment by Cyberbeni** [comment]
I've closed the ticket because nobody seemed to care about it, I don't use this tool and I wanted to clean up my open issues a bit. I've just did a search on GitHub after fixing this same issue for the 3rd or 4th time and opened an issue where it seemed to be an issue based on a quick glance at the code.

**Comment by OdNairy** [comment]
@Cyberbeni I just want to thank you for this ticket. While I'm not a maintainer of this repo, I'm watching it for useful tips and this is one of them.
I've implemented the suggested build setting in the Mapbox Maps SDK.
https://github.com/mapbox/mapbox-maps-ios/commit/84b7724ca0194a7bde144fa6ed42092be29f8e9e
