### ISSUE TITLE
Distributing XCFramework via SPM

### ISSUE THREAD

**Issue by Parabak** [bielikb/xcframeworks#5]
Hi Boris,

Swift 5.2 was released recently and if I got it right, distributing XCFramework via SPM was part of changes [here](https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md#new-packagedescription-api). Do you know something about it? How I should format Swift.package to make it work?

Best regards, 
Alex.

**Comment by bielikb** [comment]
Hi @Parabak, 
indeed the implementation of **SE-0272** is already in place (master), but it wasnt part of the latest Swift 5.2 release.

The support for binary dependencies in SPM (among others) will be introduced in following releases, as stated [here](https://forums.swift.org/t/accepted-with-modifications-se-0272-package-manager-binary-dependencies/31926/9)

**Comment by Parabak** [comment]
Thanks a lot for quick response! Obviously I misunderstood that msg. It says in a next major version, so it will be 6.0, right?

**Comment by bielikb** [comment]
Yeah, it appears so. 
All SPM related proposals (binary dependencies, support for resources) need also good integration with Xcode through `libSwiftPM`, my hope's we will see that during this year WWDC with introduction of `Xcode 12.0`
