### ISSUE TITLE
Embed XCFramework using Run script phase

### ISSUE THREAD

**Issue by GRyabkin** [bielikb/xcframeworks#6]
I have found [the way](https://stackoverflow.com/questions/40400086/xcode-add-embedded-binary-with-buildscript) on how to embed a simple dynamic framework using `Run script` phase

Do you happen to know how to embed XCFramework using `Run script` phase?

**Comment by yurkins** [comment]
@GRyabkin Nice!

**Comment by bielikb** [comment]
Hi, 
if you're eg using the fastlane plugin to create the xcframework, you should be fine with

1. Adding an aggregate target to your project that builds the dynamic framework
<img width="493" alt="Screenshot 2020-11-02 at 19 56 10" src="https://user-images.githubusercontent.com/4924709/97908340-dc8bd580-1d46-11eb-956e-f4274504d76a.png">

2. Adding the Run script phase to the aggregated target. 
Here's en example of the script that 
```
// cd to the project folder.
cd ${SRCROOT} #  Please note that if `fastlane` folder is not present as a subfolder of this project folder you might want run additional `cd ..` command

// run the lane that builds the xcframework
bundle exec fastlane export_xcframework
```

**Comment by GRyabkin** [comment]
Hey dude, I had the aggregate target before. I wanted to simplify by using fastlane for my CI. Looks like it doesn't work.

**Comment by bielikb** [comment]
Can you please clarigy what exactly you're trying to achieve? I lack details about your current setup and what's the final goal you try to achieve, so any direction or information would be helpful ;)

**Comment by GRyabkin** [comment]
I want to make your fastlane action to work

**Comment by GRyabkin** [comment]
I want to build xcframework of my SDK

**Comment by GRyabkin** [comment]
I have my Bundle name set as `$(PRODUCT_NAME)` maybe if I hardcode it helps but it strange that its not taken into account. Also, look `fastlane` action `xcodebuild` has `derivedDataPath` parameter I am surprised that you recommend me to `cd` to folder where derived data will be generated

**Comment by GRyabkin** [comment]
Two archives succeded but the error looking into logs happens at combining them I guess

**Comment by bielikb** [comment]
Im afraid that without the demo project/setup that reproduces your issue I won't be able to help you.

**Comment by bielikb** [comment]
Have you tried to not use the product name param? Will you get the same result?

**Comment by GRyabkin** [comment]
Forget, I will try to finish it up with fastlane action

**Comment by GRyabkin** [comment]
The question was about Embedding xcframework into project, not building it
